const state = {
    projecttemplates: [{
            temID: "tem000",
            temName: "空白",
            icon: ":iconfont icon-wendang",
            desc: "",
            projecttypes: "",
            projectpic: [],
            projectstation: "",
            projectcomment: "",
            projectcustomer: "",
            projectmembers: [],
            projectlifttime: "",
            devicesubtypes: [],
        }, {
            temID: "tem001",
            temName: "设备案例",
            icon: ":iconfont icon-moban",
            desc: "",
            projecttypes: "fruit",
            projectpic: ['Apple'],
            projectstation: "",
            projectcomment: "",
            projectcustomer: "",
            projectmembers: ['Apple', 'Blood Orange', 'Cantaloupe', ],
            projectlifttime: "",
            devicesubtypes: ['备件', '机械', '液压', '气动', ],
        },
        {
            temID: "tem002",
            temName: "加工示例",
            icon: ":iconfont icon-moban",
            projecttypes: "fruit",
            projectpic: ['Blood'],
            projectstation: "",
            projectcomment: "",
            projectcustomer: "",
            projectmembers: ['Apple', 'Blood Orange', 'Cantaloupe', ],
            projectlifttime: "",
            devicesubtypes: ['备件', '机械', '液压', '气动', ],
        },
        {
            temID: "tem003",
            temName: "贸易示例",
            icon: ":iconfont icon-moban",
            projecttypes: "fruit",
            projectpic: ['Cantaloupe', ],
            projectstation: "",
            projectcomment: "",
            projectcustomer: "",
            projectmembers: ['Apple', 'Blood Orange', 'Cantaloupe', ],
            projectlifttime: "",
            devicesubtypes: ['备件', '机械', '液压', '气动', ],
        },
        {
            temID: "tem004",
            temName: "Orange",
            icon: ":iconfont icon-moban",
            projecttypes: "fruit",
            projectpic: ['Orange'],
            projectstation: "",
            projectcomment: "",
            projectcustomer: "",
            projectmembers: ['Apple', 'Blood Orange', 'Cantaloupe', ],
            projectlifttime: "",
            devicesubtypes: ['备件', '机械', '液压', '气动', ],
        },
    ],
    projecttypes: ['Apple', 'Blood Orange', 'Cantaloupe', ],
    devicesubtypes: ['备件', '机械', '液压', '气动', '程序', ],
}
const getters = {
    projecttemplates(state) {
        return state.projecttemplates
    },
}
export default {
    state,
    getters,
    mutations: {},
    actions: {}
};